training_config:
  seed: 42
  mixed_bf16_precision: true
  reshard_after_forward: false
  num_to_explicit_prefetching: null
  gradient_checkpointing: true
  dcp_api: false
  learning_rate: 5e-6
  grad_accum_steps: 1
  log_interval: 1
  validation_steps: 1000
  max_grad_norm: 1.0
  save_interval: 1000
  enable_ema: true
  output_dir: "checkpoints/all_data"
  wandb_proj_name: "qwen-image-edit-train"
  wandb_run_name: "all_data"
  weight_init: "/mnt/data/checkpoints/Qwen/Qwen-Image-Edit/transformer/merged.pt"
  resume_from_checkpoint: "latest"

model_config:
  condition_encoder_name_or_path: "/mnt/data/checkpoints/Qwen/Qwen-Image-Edit/text_encoder"
  condition_processor_name_or_path: "/mnt/data/checkpoints/Qwen/Qwen-Image-Edit/processor"
  vae_name_or_path: "/mnt/data/checkpoints/Qwen/Qwen-Image-Edit/vae"
  scheduler_name_or_path: "/mnt/data/checkpoints/Qwen/Qwen-Image-Edit/scheduler"

dataset_config:
  data_txt: /mnt/data/lb/FSDP-Training/configs/all_data.txt
  val_data_txt: /mnt/data/lb/FSDP-Training/configs/all_val_data.txt
  batch_size: 1
  num_workers: 12
  reversed_text_edit_ratio: 0.67
  box_guidance_text_edit_ratio: 0.5