training_config:
  seed: 42
  mixed_bf16_precision: true
  reshard_after_forward: true
  num_to_explicit_prefetching: null
  gradient_checkpointing: true
  dcp_api: false
  learning_rate: 1e-5
  grad_accum_steps: 1
  log_interval: 1
  validation_steps: 5
  max_grad_norm: 1.0
  save_interval: 5
  enable_ema: true
  ema_decay: 0.0
  output_dir: "checkpoints/test_ema"
  wandb_proj_name: "qwen-image-edit-train"
  wandb_run_name: "test_ema"
  weight_init: null
  resume_from_checkpoint: "latest"

model_config:
  condition_encoder_name_or_path: "/mnt/data/checkpoints/Qwen/Qwen-Image-Edit/text_encoder"
  condition_processor_name_or_path: "/mnt/data/checkpoints/Qwen/Qwen-Image-Edit/processor"
  vae_name_or_path: "/mnt/data/checkpoints/Qwen/Qwen-Image-Edit/vae"
  scheduler_name_or_path: "/mnt/data/checkpoints/Qwen/Qwen-Image-Edit/scheduler"
  test_num_layers: 2
 
dataset_config:
  data_txt: /mnt/data/lb/FSDP-Training/configs/test.txt
  val_data_txt: /mnt/data/lb/FSDP-Training/configs/test_val.txt
  batch_size: 1
  num_workers: 12
  reversed_text_edit_ratio: 0.67
  box_guidance_text_edit_ratio: 0.5