training_config:
  seed: 42
  mixed_bf16_precision: true
  gradient_checkpointing: true
  dcp_api: false
  learning_rate: 1e-5
  grad_accum_steps: 1
  log_interval: 1
  validation_steps: 250
  max_grad_norm: 1.0
  save_interval: 250
  wandb_proj_name: "qwen-image-edit-train"
  wandb_run_name: "test_edit"
  weight_init: "/mnt/data/checkpoints/Qwen/Qwen-Image-Edit/transformer/merged.pt"
  resume_from_checkpoint: "latest"

model_config:
  condition_encoder_name_or_path: "/mnt/data/checkpoints/Qwen/Qwen-Image-Edit/text_encoder"
  condition_processor_name_or_path: "/mnt/data/checkpoints/Qwen/Qwen-Image-Edit/processor"
  vae_name_or_path: "/mnt/data/checkpoints/Qwen/Qwen-Image-Edit/vae"
  scheduler_name_or_path: "/mnt/data/checkpoints/Qwen/Qwen-Image-Edit/scheduler"

dataset_config:
  data_txt: /mnt/data/lb/FSDP-Training/configs/text_edit_data.txt
  val_data_txt: /mnt/data/lb/FSDP-Training/configs/text_edit_val_data.txt
  batch_size: 1
  num_workers: 8